### ISSUE TITLE
When our why to use instead of plain Nikola?

### ISSUE THREAD

**Issue by hartwork** [ralsina/nikola-server#6]
Hi!

It would be great to have a quick line in the readme or the repository description explaining when or why nikola-server can be of use over plain Nikola.

Thanks!

**Comment by ralsina** [comment]
This is obsolete stuff, has not been touched in 5 years.

**Comment by hartwork** [comment]
Can we add a big "OBSOLETE" marker somewhere?

**Comment by ralsina** [comment]
It's not published anywhere in the nikola site or docs.
